CREATE SCHEMA IF NOT EXISTS BL_DM;

-- DIM_CUSTOMERS: SCD1 table with source triplet; stores customer names and phone numbers.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CUSTOMERS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PHONE_NUMBER VARCHAR(22) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_DISCOUNTS: SCD1 table with source triplet; stores discount percentage and discount date.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_DISCOUNT START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_DISCOUNTS (
    DISCOUNT_ID BIGINT PRIMARY KEY,
    DISCOUNT_PERCENTAGE DECIMAL(5, 2) NOT NULL,
    DISCOUNT_DATE DATE NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_EMPLOYEES: SCD1 table with source triplet;
-- stores employee personal details including unique personal ID and phone.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_EMPLOYEES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEES (
    EMP_ID BIGINT PRIMARY KEY,
    EMP_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    DOB_DT DATE NOT NULL,
    PERSONAL_ID VARCHAR(12) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(18) NOT NULL UNIQUE,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);



-- DIM_POINTS: SCD1 table with source triplet; stores sales point names and full addresses.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_POINTS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_POINTS (
    POINT_ID BIGINT PRIMARY KEY,
    POINT_SRC_ID VARCHAR(255) NOT NULL,
    POINT_NAME VARCHAR(64) NOT NULL,
    POINT_ADDRESS_ID BIGINT NOT NULL,
    POINT_ADDRESS VARCHAR (64) NOT NULL,
    POINT_CITY_ID BIGINT NOT NULL,
    POINT_CITY_NAME VARCHAR (64) NOT NULL,
    POINT_COUNTRY_ID BIGINT NOT NULL,
    POINT_COUNTRY_NAME VARCHAR (64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);


-- DIM_CARD_INFORMATION: SCD1 table with source triplet; combines bank and card type info for card-based transactions.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CARD_INFORMATION START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CARD_INFORMATIONS (
    CARD_INFORMATION_ID BIGINT PRIMARY KEY,
    CARD_INFORMATION_SRC_ID VARCHAR(255) NOT NULL,
    CARD_BANK_ID BIGINT NOT NULL,
    CARD_BANK_NAME VARCHAR(64) NOT NULL,
    CARD_TYPE_ID BIGINT NOT NULL,
    CARD_TYPE_NAME VARCHAR(64)NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_CHANNELS SCD1 TABLE WITH SOURCE TRIPLET; STORES CHANNEL NAMES AND DESCRIPTIONS.
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CHANNELS START WITH 1;
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CHANNELS (
    CHANNEL_ID BIGINT PRIMARY KEY,
    CHANNEL_SRC_ID VARCHAR(255) NOT NULL,
    CHANNEL_NAME VARCHAR(64) NOT NULL,
    CHANNEL_DESC VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_DATES
CREATE TABLE IF NOT EXISTS bl_dm.dim_dates (
    date_id DATE PRIMARY KEY,
    year INT NOT NULL,
    quarter INT NOT NULL,
    month INT NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    day INT NOT NULL,
    day_of_week INT NOT NULL,
    day_name VARCHAR(20) NOT NULL
);

-- DIM_PRODUCTS_SCD: SCD2 table with source triplet and historical tracking; contains product names, categoies, and active periods.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PRODUCTS_SCD START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SCD (
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CATEGORY_ID BIGINT NOT NULL,
    PRODUCT_CATEGORY_NAME VARCHAR(255) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    PRIMARY KEY (PRODUCT_ID,
START_DT)
);


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_channels_src'
    ) THEN
        ALTER TABLE bl_dm.dim_channels
        ADD CONSTRAINT uq_dim_channels_src UNIQUE (channel_src_id, source_system, source_entity);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_customers_src'
    ) THEN
        ALTER TABLE bl_dm.dim_customers
        ADD CONSTRAINT uq_dim_customers_src UNIQUE (customer_src_id, source_system, source_entity);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_employees_src'
    ) THEN
        ALTER TABLE bl_dm.dim_employees
        ADD CONSTRAINT uq_dim_employees_src UNIQUE (personal_id, source_system, source_entity);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_discounts_src'
    ) THEN
        ALTER TABLE bl_dm.dim_discounts
        ADD CONSTRAINT uq_dim_discounts_src UNIQUE (source_id, source_system, source_entity);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_card_informations_src'
    ) THEN
        ALTER TABLE bl_dm.dim_card_informations
        ADD CONSTRAINT uq_dim_card_informations_src UNIQUE (card_information_src_id, source_system, source_entity);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_points_src'
    ) THEN
        ALTER TABLE bl_dm.dim_points
        ADD CONSTRAINT uq_dim_points_src UNIQUE (point_src_id, source_system, source_entity);
    END IF;
END
$$;

