CREATE SCHEMA IF NOT EXISTS BL_DM;

-- DIM_CHANNELS SCD1 TABLE WITH SOURCE TRIPLET; STORES CHANNEL NAMES AND DESCRIPTIONS.
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CHANNELS START WITH 1;
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CHANNELS (
    CHANNEL_ID BIGINT PRIMARY KEY,
    CHANNEL_SRC_ID VARCHAR(255) NOT NULL,
    CHANNEL_NAME VARCHAR(64) NOT NULL,
    CHANNEL_DESC VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_channels_src'
    ) THEN
        ALTER TABLE bl_dm.dim_channels
        ADD CONSTRAINT uq_dim_channels_src UNIQUE (channel_src_id, source_system, source_entity);
    END IF;

END
$$;