CREATE SCHEMA IF NOT EXISTS BL_DM;

-- DIM_PRODUCTS_SCD: SCD2 table with source triplet and historical tracking; contains product names, categoies, and active periods.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PRODUCTS_SCD START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SCD (
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CATEGORY_ID BIGINT NOT NULL,
    PRODUCT_CATEGORY_NAME VARCHAR(255) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    PRIMARY KEY (PRODUCT_ID,
START_DT)
);
