CREATE SCHEMA IF NOT EXISTS BL_DM;

-- DIM_POINTS: SCD1 table with source triplet; stores sales point names and full addresses.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_POINTS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_POINTS (
    POINT_ID BIGINT PRIMARY KEY,
    POINT_SRC_ID VARCHAR(255) NOT NULL,
    POINT_NAME VARCHAR(64) NOT NULL,
    POINT_ADDRESS_ID BIGINT NOT NULL,
    POINT_ADDRESS VARCHAR (64) NOT NULL,
    POINT_CITY_ID BIGINT NOT NULL,
    POINT_CITY_NAME VARCHAR (64) NOT NULL,
    POINT_COUNTRY_ID BIGINT NOT NULL,
    POINT_COUNTRY_NAME VARCHAR (64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

DO $$
BEGIN

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_dim_points_src'
    ) THEN
        ALTER TABLE bl_dm.dim_points
        ADD CONSTRAINT uq_dim_points_src UNIQUE (point_src_id, source_system, source_entity);
    END IF;
END
$$;