--DROP TABLE bl_dm.fct_sales_dd;
--DROP SEQUENCE BL_DM.SEQ_DIM_SALES;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_SALES START WITH 1;
CREATE TABLE IF NOT EXISTS BL_DM.FCT_SALES_DD (
    SALES_ID BIGINT NOT NULL,
    EVENT_DT DATE NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    DISCOUNT_ID BIGINT NOT NULL,
    FCT_QUANTITY INT NOT NULL,
    FCT_PRODUCT_PRICE DECIMAL(6, 2) NOT NULL,
    FCT_PAYMENT_AMOUNT DECIMAL(6, 2) NOT NULL,
    PAYMENT_TYPE VARCHAR(4) NOT NULL CHECK (PAYMENT_TYPE IN ('CASH', 'CARD')),
    POINT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    CARD_INFORMATION_ID BIGINT NOT NULL,
    CHANNEL_ID BIGINT NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL,
    CONSTRAINT fct_sales_dd_pkey PRIMARY KEY (sales_id, event_dt)
) PARTITION BY RANGE (event_dt);

-- Q1 2024
CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_2024_q1
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');

-- Q2 2024
CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_2024_q2
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2024-04-01') TO ('2024-07-01');

-- Q3 2024
CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_2024_q3
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2024-07-01') TO ('2024-10-01');

-- Q4 2024
CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_2024_q4
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2024-10-01') TO ('2025-01-01');

-- Q1 2025
CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_2025_q1
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2025-01-01') TO ('2025-04-01');

-- Q2 2025
CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_2025_q2
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2025-04-01') TO ('2025-07-01');