CREATE SCHEMA IF NOT EXISTS BL_DM;

-- DIM_CUSTOMERS: SCD1 table with source triplet; stores customer names and phone numbers.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CUSTOMERS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PHONE_NUMBER VARCHAR(22) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_DISCOUNTS: SCD1 table with source triplet; stores discount percentage and discount date.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_DISCOUNT START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_DISCOUNTS (
    DISCOUNT_ID BIGINT PRIMARY KEY,
    DISCOUNT_PERCENTAGE DECIMAL(5, 2) NOT NULL,
    DISCOUNT_DATE DATE NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_EMPLOYEES: SCD1 table with source triplet;
-- stores employee personal details including unique personal ID and phone.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_EMPLOYEES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEES (
    EMP_ID BIGINT PRIMARY KEY,
    EMP_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    DOB_DT DATE NOT NULL,
    PERSONAL_ID VARCHAR(12) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(18) NOT NULL UNIQUE,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);



-- DIM_POINTS: SCD1 table with source triplet; stores sales point names and full addresses.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_POINTS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_POINTS (
    POINT_ID BIGINT PRIMARY KEY,
    POINT_SRC_ID VARCHAR(255) NOT NULL,
    POINT_NAME VARCHAR(64) NOT NULL,
    POINT_ADDRESS_ID BIGINT NOT NULL,
    POINT_ADDRESS VARCHAR (64) NOT NULL,
    POINT_CITY_ID BIGINT NOT NULL,
    POINT_CITY_NAME VARCHAR (64) NOT NULL,
    POINT_COUNTRY_ID BIGINT NOT NULL,
    POINT_COUNTRY_NAME VARCHAR (64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);


-- DIM_CARD_INFORMATION: SCD1 table with source triplet; combines bank and card type info for card-based transactions.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CARD_INFORMATION START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CARD_INFORMATIONS (
    CARD_INFORMATION_ID BIGINT PRIMARY KEY,
    CARD_INFORMATION_SRC_ID VARCHAR(255) NOT NULL,
    CARD_BANK_ID BIGINT NOT NULL,
    CARD_BANK_NAME VARCHAR(64) NOT NULL,
    CARD_TYPE_ID BIGINT NOT NULL,
    CARD_TYPE_NAME VARCHAR(64)NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_CHANNELS SCD1 TABLE WITH SOURCE TRIPLET; STORES CHANNEL NAMES AND DESCRIPTIONS.
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CHANNELS START WITH 1;
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CHANNELS (
    CHANNEL_ID BIGINT PRIMARY KEY,
    CHANNEL_SRC_ID VARCHAR(255) NOT NULL,
    CHANNEL_NAME VARCHAR(64) NOT NULL,
    CHANNEL_DESC VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- DIM_PRODUCTS_SCD: SCD2 table with source triplet and historical tracking; contains product names, categoies, and active periods.

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PRODUCTS_SCD START WITH 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SCD (
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CATEGORY_ID BIGINT NOT NULL,
    PRODUCT_CATEGORY_NAME VARCHAR(255) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    PRIMARY KEY (PRODUCT_ID,
START_DT)
);

-- FCT_SALES_DD: Fact table with event date and surrogate keys to dimensions; contains transactional sales data.


CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_SALES START WITH 1;
CREATE TABLE IF NOT EXISTS BL_DM.FCT_SALES_DD (
    SALES_ID BIGINT PRIMARY KEY,
    EVENT_DT DATE NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    DISCOUNT_ID BIGINT NOT NULL,
    FCT_QUANTITY INT NOT NULL,
    FCT_PRODUCT_PRICE DECIMAL(6, 2) NOT NULL,
    FCT_PAYMENT_AMOUNT DECIMAL(6, 2) NOT NULL,
    PAYMENT_TYPE VARCHAR(4) NOT NULL CHECK (PAYMENT_TYPE IN ('CASH', 'CARD')),
    POINT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    CARD_INFORMATION_ID BIGINT NOT NULL,
    CHANNEL_ID BIGINT NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

COMMIT;

ALTER TABLE bl_dm.dim_channels
ADD CONSTRAINT uq_dim_channels_src UNIQUE (channel_src_id, source_system, source_entity);

ALTER TABLE bl_dm.dim_customers
ADD CONSTRAINT uq_dim_customers_src UNIQUE (customer_src_id, source_system, source_entity);

ALTER TABLE bl_dm.dim_employees
ADD CONSTRAINT uq_dim_employees_src UNIQUE (personal_id, source_system, source_entity);
ALTER TABLE bl_dm.dim_employees
ALTER COLUMN phone_number TYPE VARCHAR(18);

ALTER TABLE bl_dm.dim_discounts
ADD CONSTRAINT uq_dim_discounts_src UNIQUE (source_id, source_system, source_entity);

ALTER TABLE bl_dm.dim_card_informations
ADD CONSTRAINT uq_dim_card_informations_src UNIQUE (card_information_src_id, source_system, source_entity);

ALTER TABLE bl_dm.dim_points
ADD CONSTRAINT uq_dim_points_src UNIQUE (point_src_id, source_system, source_entity);


--DEFAULT ROWS
-- DIM_CUSTOMERS
INSERT INTO BL_DM.DIM_CUSTOMERS (
    CUSTOMER_ID,
    CUSTOMER_SRC_ID,
    FIRST_NAME,
    LAST_NAME,
    PHONE_NUMBER,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT,
    TA_UPDATE_DT
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_CUSTOMERS WHERE CUSTOMER_ID = -1
);

-- DIM_DISCOUNTS
INSERT INTO BL_DM.DIM_DISCOUNTS (
    DISCOUNT_ID,
    DISCOUNT_PERCENTAGE,
    DISCOUNT_DATE,
    SOURCE_ID,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT,
    TA_UPDATE_DT
)
SELECT
    -1,
    0.00,
    DATE '1990-01-01',
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_DISCOUNTS WHERE DISCOUNT_ID = -1
);

-- DIM_EMPLOYEES
INSERT INTO BL_DM.DIM_EMPLOYEES (
    EMP_ID,
    EMP_SRC_ID,
    FIRST_NAME,
    LAST_NAME,
    DOB_DT,
    PERSONAL_ID,
    PHONE_NUMBER,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT,
    TA_UPDATE_DT
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    DATE '1990-01-01',
    'n.a.',
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_EMPLOYEES WHERE EMP_ID = -1
);

-- DIM_POINTS
INSERT INTO BL_DM.DIM_POINTS (
    POINT_ID,
    POINT_SRC_ID,
    POINT_NAME,
    POINT_ADDRESS_ID,
    POINT_ADDRESS,
    POINT_CITY_ID,
    POINT_CITY_NAME,
    POINT_COUNTRY_ID,
    POINT_COUNTRY_NAME,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT,
    TA_UPDATE_DT
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_POINTS WHERE POINT_ID = -1
);

-- DIM_CARD_INFORMATIONS
INSERT INTO BL_DM.DIM_CARD_INFORMATIONS (
    CARD_INFORMATION_ID,
    CARD_INFORMATION_SRC_ID,
    CARD_BANK_ID,
    CARD_BANK_NAME,
    CARD_TYPE_ID,
    CARD_TYPE_NAME,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT,
    TA_UPDATE_DT
)
SELECT
    -1,
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_CARD_INFORMATIONS WHERE CARD_INFORMATION_ID = -1
);

-- DIM_CHANNELS
INSERT INTO BL_DM.DIM_CHANNELS (
    CHANNEL_ID,
    CHANNEL_SRC_ID,
    CHANNEL_NAME,
    CHANNEL_DESC,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT,
    TA_UPDATE_DT
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_CHANNELS WHERE CHANNEL_ID = -1
);

-- DIM_PRODUCTS_SCD (SCD2)
INSERT INTO BL_DM.DIM_PRODUCTS_SCD (
    PRODUCT_ID,
    PRODUCT_SRC_ID,
    PRODUCT_NAME,
    PRODUCT_CATEGORY_ID,
    PRODUCT_CATEGORY_NAME,
    START_DT,
    END_DT,
    IS_ACTIVE,
    SOURCE_ID,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    TA_INSERT_DT
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    -1,
    'n.a.',
    DATE '1990-01-01',
    DATE '2999-12-31',
    'Y',
    'n.a.',
    'manual',
    'manual',
    CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM BL_DM.DIM_PRODUCTS_SCD
    WHERE PRODUCT_ID = -1 AND START_DT = DATE '1990-01-01'
);
COMMIT ;