CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- CE_CUSTOMERS: SCD1 table with source triplet; stores customer names and phone numbers.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CUSTOMERS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PHONE_NUMBER VARCHAR(22) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_DISCOUNTS: SCD1 table with source triplet; stores discount percentage and discount date.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DISCOUNT START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_DISCOUNTS (
    DISCOUNT_ID BIGINT PRIMARY KEY,
    DISCOUNT_PERCENTAGE DECIMAL(5, 2) NOT NULL,
    DISCOUNT_DATE DATE NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- bl_3nf.ce_channels channel where order was done
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CHANNEL START WITH 1;

CREATE TABLE bl_3nf.ce_channels (
	channel_id BIGINT PRIMARY KEY,
	channel_src_id varchar(255) NOT NULL,
	channel_name varchar(64) NOT NULL,
	channel_desc varchar(255) NOT NULL,
	source_system varchar(255) NOT NULL,
	source_entity varchar(255) NOT NULL,
	ta_insert_dt date NOT NULL,
	ta_update_dt date NOT NULL
);
-- CE_EMPLOYEES: SCD1 table with source triplet;
-- stores employee personal details including unique personal ID and phone.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_EMPLOYEES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES (
    EMP_ID BIGINT PRIMARY KEY,
    EMP_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    DOB DATE NOT NULL,
    PERSONAL_ID VARCHAR(12) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);


-- CE_COUNTRIES: SCD1 table with source triplet; stores names of countries where sales points are located.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_COUNTRY START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES (
    COUNTRY_ID BIGINT PRIMARY KEY,
    COUNTRY_SRC_ID VARCHAR(255) NOT NULL,
    COUNTRY_NAME VARCHAR(64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_CITIES: SCD1 table with source triplet; stores city names and logically linked to CE_COUNTRY.
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CITY START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES(
	CITY_ID BIGINT PRIMARY KEY,
	CITY_SRC_ID VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(64) NOT NULL,
	COUNTRY_ID BIGINT NOT NULL,
	SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
	TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_ADDRESSE: SCD1 table with source triplet; stores physical addresses and is linked to CE_CITY.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_ADDRESS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_ADDRESSES (
    ADDRESS_ID BIGINT PRIMARY KEY,
    ADDRESS_SRC_ID VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(64) NOT NULL,
    CITY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CITIES(CITY_ID),
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_POINTS: SCD1 table with source triplet; stores sales point names and links to CE_ADDRESS.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_POINTS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_POINTS (
    POINT_ID BIGINT PRIMARY KEY,
    POINT_SRC_ID VARCHAR(255) NOT NULL,
    POINT_NAME VARCHAR(64) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID),
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_BANKS: SCD1 table with source triplet; contains names of banks used in card payments.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_BANKS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_BANKS (
    BANK_ID BIGINT PRIMARY KEY,
    BANK_SRC_ID VARCHAR(255) NOT NULL,
    BANK_NAME VARCHAR(64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_CARD_TYPES: SCD1 table with source triplet; contains card type names (e.g., Visa, MasterCard).

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CARD_TYPES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CARD_TYPES (
    CARD_TYPE_ID BIGINT PRIMARY KEY,
    CARD_TYPE_SRC_ID VARCHAR(255) NOT NULL,
    CARD_TYPE_NAME VARCHAR(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_CARD_INFORMATION: SCD1 table with source triplet; combines bank and card type info for card-based transactions.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CARD_INFORMATION START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CARD_INFORMATIONS (
    CARD_INFORMATION_ID BIGINT PRIMARY KEY,
    CARD_INFORMATION_SRC_ID VARCHAR(255) NOT NULL,
    BANK_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_BANKS(BANK_ID),
    CARD_TYPE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CARD_TYPES(CARD_TYPE_ID),
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);


-- CE_CATEGORIES: SCD1 table with source triplet; stores product category names.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CATEGORIES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CATEGORIES (
    CATEGORY_ID BIGINT PRIMARY KEY,
    CATEGORY_SRC_ID VARCHAR(255) NOT NULL,
    CATEGORY_NAME VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_PRODUCTS_SCD: SCD2 table with source triplet and historical tracking; contains product names, category links, and active periods.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PRODUCTS_SCD START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS_SCD (
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CATEGORIES(CATEGORY_ID),
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    PRIMARY KEY (PRODUCT_ID,
START_DT)
);

-- CE_SALES: Fact table with event date and surrogate keys to dimensions; contains transactional sales data.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_SALES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
    SALES_ID BIGINT PRIMARY KEY,
    EVENT_DT DATE NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    DISCOUNT_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_DISCOUNTS(DISCOUNT_ID),
    PRODUCT_PRICE DECIMAL(6, 2) NOT NULL,
    PRODUCT_QUANTITY INTEGER NOT NULL,
    PAYMENT_AMOUNT DECIMAL(6, 2) NOT NULL,
    PAYMENT_TYPE VARCHAR(4) NOT NULL CHECK (PAYMENT_TYPE IN ('CASH', 'CARD')),
    POINT_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_POINTS(POINT_ID),
    CUSTOMER_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CUSTOMERS(CUSTOMER_ID),
    EMPLOYEE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_EMPLOYEES(EMP_ID),
    CARD_INFORMATION_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CARD_INFORMATIONS(CARD_INFORMATION_ID),
    CHANNEL_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CHANNELs(CHANNEL_ID),
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);