-- CE_BANKS: SCD1 table with source triplet; contains names of banks used in card payments.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_BANKS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_BANKS (
    BANK_ID BIGINT PRIMARY KEY,
    BANK_SRC_ID VARCHAR(255) NOT NULL,
    BANK_NAME VARCHAR(64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_CARD_TYPES: SCD1 table with source triplet; contains card type names (e.g., Visa, MasterCard).

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CARD_TYPES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CARD_TYPES (
    CARD_TYPE_ID BIGINT PRIMARY KEY,
    CARD_TYPE_SRC_ID VARCHAR(255) NOT NULL,
    CARD_TYPE_NAME VARCHAR(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_CARD_INFORMATION: SCD1 table with source triplet; combines bank and card type info for card-based transactions.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CARD_INFORMATION START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CARD_INFORMATIONS (
    CARD_INFORMATION_ID BIGINT PRIMARY KEY,
    CARD_INFORMATION_SRC_ID VARCHAR(255) NOT NULL,
    BANK_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_BANKS(BANK_ID),
    CARD_TYPE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CARD_TYPES(CARD_TYPE_ID),
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);