CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- CE_CUSTOMERS: SCD1 table with source triplet; stores customer names and phone numbers.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CUSTOMERS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PHONE_NUMBER VARCHAR(22) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);
