-- CE_DISCOUNTS: SCD1 table with source triplet; stores discount percentage and discount date.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DISCOUNT START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_DISCOUNTS (
    DISCOUNT_ID BIGINT PRIMARY KEY,
    DISCOUNT_PERCENTAGE DECIMAL(5, 2) NOT NULL,
    DISCOUNT_DATE DATE NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);