-- CE_EMPLOYEES: SCD1 table with source triplet;
-- stores employee personal details including unique personal ID and phone.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_EMPLOYEES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES (
    EMP_ID BIGINT PRIMARY KEY,
    EMP_SRC_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    DOB DATE NOT NULL,
    PERSONAL_ID VARCHAR(12) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);