-- CE_SALES: Fact table with event date and surrogate keys to dimensions; contains transactional sales data.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_SALES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
    SALES_ID BIGINT PRIMARY KEY,
    EVENT_DT DATE NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    DISCOUNT_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_DISCOUNTS(DISCOUNT_ID),
    PRODUCT_PRICE DECIMAL(6, 2) NOT NULL,
    PRODUCT_QUANTITY INTEGER NOT NULL,
    PAYMENT_AMOUNT DECIMAL(6, 2) NOT NULL,
    PAYMENT_TYPE VARCHAR(4) NOT NULL CHECK (PAYMENT_TYPE IN ('CASH', 'CARD')),
    POINT_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_POINTS(POINT_ID),
    CUSTOMER_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CUSTOMERS(CUSTOMER_ID),
    EMPLOYEE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_EMPLOYEES(EMP_ID),
    CARD_INFORMATION_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CARD_INFORMATIONS(CARD_INFORMATION_ID),
    CHANNEL_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CHANNELs(CHANNEL_ID),
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);