-- CE_COUNTRIES: SCD1 table with source triplet; stores names of countries where sales points are located.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_COUNTRY START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES (
    COUNTRY_ID BIGINT PRIMARY KEY,
    COUNTRY_SRC_ID VARCHAR(255) NOT NULL,
    COUNTRY_NAME VARCHAR(64) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_CITIES: SCD1 table with source triplet; stores city names and logically linked to CE_COUNTRY.
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CITY START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES(
	CITY_ID BIGINT PRIMARY KEY,
	CITY_SRC_ID VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(64) NOT NULL,
	COUNTRY_ID BIGINT NOT NULL,
	SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
	TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_ADDRESSE: SCD1 table with source triplet; stores physical addresses and is linked to CE_CITY.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_ADDRESS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_ADDRESSES (
    ADDRESS_ID BIGINT PRIMARY KEY,
    ADDRESS_SRC_ID VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(64) NOT NULL,
    CITY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CITIES(CITY_ID),
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_POINTS: SCD1 table with source triplet; stores sales point names and links to CE_ADDRESS.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_POINTS START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_POINTS (
    POINT_ID BIGINT PRIMARY KEY,
    POINT_SRC_ID VARCHAR(255) NOT NULL,
    POINT_NAME VARCHAR(64) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID),
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);