-- CE_CATEGORIES: SCD1 table with source triplet; stores product category names.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CATEGORIES START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CATEGORIES (
    CATEGORY_ID BIGINT PRIMARY KEY,
    CATEGORY_SRC_ID VARCHAR(255) NOT NULL,
    CATEGORY_NAME VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    TA_UPDATE_DT DATE NOT NULL
);

-- CE_PRODUCTS_SCD: SCD2 table with source triplet and historical tracking; contains product names, category links, and active periods.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PRODUCTS_SCD START WITH 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS_SCD (
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CATEGORIES(CATEGORY_ID),
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    SOURCE_ENTITY VARCHAR(255) NOT NULL,
    TA_INSERT_DT DATE NOT NULL,
    PRIMARY KEY (PRODUCT_ID,
START_DT)
);